### ISSUE TITLE
Unable to get archery range apps to run

### ISSUE THREAD

**Issue by psiinon** [google/security-testbeds#8]
I'm not able to get the security-testbeds to run.
Obviously I may well be doing something wrong, but I believe I am following the instructions.

The steps I'm performing:

- docker pull python
- docker run -i -t python bash

Then in the docker container:

- git clone https://github.com/google/security-testbeds.git
- cd /security-testbeds/archery_range/xss
- pip3 install -r requirements.txt
- python3 app.py

This fails:
```
root@b0611616034f:/security-testbeds/archery_range/xss# python3 app.py
Traceback (most recent call last):
  File "/security-testbeds/archery_range/xss/app.py", line 16, in <module>
    import flask
  File "/usr/local/lib/python3.12/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.12/site-packages/werkzeug/urls.py). Did you mean: 'unquote'?
```

The sqli and xxs apps fail in the same way.

**Comment by psiinon** [comment]
https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls
Appending `Werkzeug==2.2.2` to requirements.txt seems to be a workaround..

**Comment by tooryx** [comment]
I suspect that this is obsolete. Feel free to reopen if this is not the case.

_~tooryx_
